# Generated by Django 4.0.4 on 2022-04-14 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='git',
            field=models.URLField(default='https://github.com/Sieva-cmd', max_length=400),
        ),
    ]
