# Generated by Django 4.0.4 on 2022-04-19 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_profile_git'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='linkedIn',
            field=models.URLField(default='https://www.linkedin.com/in/sieva-musyoka-18a730227/', max_length=100),
        ),
    ]
